services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - GOnet
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

    networks:
      - GOnet

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

    networks:
      - GOnet

volumes:
  mongodb_data_container:
  images_data:
    external: false
  grafana_data:
    external: false

networks:
  GOnet:
    driver: bridge
