services:
  AuctionService:
    image: asnielsen789/auctionservice:latest
    environment:
    - connectionString=mongodb://admin:1234@mongodb-dev:27017
    - databaseName=GODB
    - collectionName=auctions
   
    expose:
    - "80"
    volumes:
    - mongodb_data_container:/data/db

    networks:
    - GOnet

  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

    ports:
    - 27018:27017
    volumes:
    - mongodb_data_container:/data/db

    networks:
    - GOnet

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - AuctionService
    ports:
      - "4000:4000"
    networks:
      - GOnet

volumes:
  mongodb_data_container:
  images_data:
    external: false

  

networks:
  GOnet:
    driver: bridge