name: Docker Image CI

on:
  pull_request:
    branches: 
      - "main"
    paths:
      - AssessmentService/**
    types:
      - closed
  push:
    branches: 
      - "develop"
    paths:
      - .github/workflows/AssessmentService_BuildDockerImage.yml

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: |
        docker login --username ${{secrets.DOCKER_USER}} --password ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image for AssessmentService
      working-directory: AssessmentService
      run: |
        docker build . --file Dockerfile --tag asnielsen789/assessmentservice:latest
    - name: Push the Docker image for AssessmentService
      run: |
        docker push asnielsen789/assessmentservice:latest