name: Docker Image CI

on:
  push:
    branches: 
      - "main"
    paths:
      - AuctionService/**
  pull_request:
    branches: 
      - "main"
    paths:
      - AuctionService/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
        env:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Build the Docker image for AuctionService
      run: docker build . --file AuctionService/Dockerfile --tag auctionservice-image:$(date +%s)
    - name: Push auctionservice-image to DockerHub
      run: docker push ${{secrets.DOCKER_USER}}/auctionservice-image:$(date +%s)


      