# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 
      - "develop"
    paths:
      - BidWorker/**
      - BidWorkerTest/**
      - .github/workflows/BidWorker_Release.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies for service
      working-directory: BidWorker
      run: |
        dotnet restore
    - name: Build Service
      working-directory: BidWorker
      run: dotnet build --no-restore
    - name: Install dependencies for test
      working-directory: BidWorkerTest
      run: |
        dotnet restore
    - name: Build Test
      working-directory: BidWorkerTest
      run: dotnet build --no-restore
    - name: Run Test
      working-directory: BidWorkerTest
      run: dotnet test --no-build --verbosity normal
    - name: Set up Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: create pull request
      run: gh pr create -B main -H develop --title 'Merge develop into main branch' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.PAT }}