name: Docker Image CI

on:
  pull_request:
    branches: 
      - "main"
    paths:
      - ItemService/**
  push:
    branches: 
      - "develop"
    paths:
      - .github/workflows/ItemService_BuildDockerImage.yml

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: |
        docker login --username ${{secrets.DOCKER_USER}} --password ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image for ItemService
      run: |
        docker build . --file ItemService/Dockerfile --tag asnielsen789/itemservice:latest
    - name: Push the Docker image for ItemService
      run: |
        docker push asnielsen789/itemservice:latest