services:
  loki:
    image: grafana/loki
    container_name: loki
    ports:
    - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
    - GOnet

  grafana:
    image: grafana/grafana:latest
    ports:
    - "3000:3000"
    networks:
    - GOnet
    volumes:
    - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
    external: false

networks:
  GOnet:
    driver: bridge