services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
    - 27018:27017
    volumes:
    - mongodb_data_container:/data/db
    networks:
    - GOnet

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - AuctionService
    ports:
      - "4000:4000"
    networks:
      - GOnet

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - GOnet
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongodb_data_container:  

networks:
  GOnet:
    driver: bridge